[operators.BEELINE-MSK]
description = "Билайн-Москва"
timeout = "60s"

tasks = [
  "Option(blink-settings, imagesEnabled=false)",

  "Navigate(https://moskva.beeline.ru/login/)",

  "WaitVisible(a._1zDj0m > span)",
  "Click(a._1zDj0m > span)",

  "SendKeys(input[name='login'], $Login)",
  "SendKeys(input[name='password'], $Password)",
  "Click(button._2_o3rJ)",

  "WaitVisible(div.Balance_infoValue_kVsT)",

  "Float(div.Balance_infoValue_kVsT, Баланс)",
  "String(tr.profileInfoRow > td.Summary_profileInfoValue_1vmb > a > span.Link_text_3J9U, Тариф)",
]
