[operators.BEELINE]
description = "Билайн"
timeout = "30s"

tasks = [
  "Navigate(https://my.beeline.ru/login.xhtml)",
  "Clear(input[id='loginFormB2C:loginForm:login'])",

  "SetValue(input[id='loginFormB2C:loginForm:login'], $Login)",
  "SetValue(input[id='loginFormB2C:loginForm:passwordPwd'], $Password)",
  "Click(button[id='loginFormB2C:loginForm:j_idt218'])",

  "Float(div.Balance_infoValue_kVsT, Баланс)",
  "String(tr.profileInfoRow > td.Summary_profileInfoValue_1vmb > a > span.Link_text_3J9U, Тариф)",
]
