[operators.BEELINE-MSK]
description = "Билайн-Москва"
timeout = "120s"

tasks = [
  "Option(blink-settings, imagesEnabled=true)",

  "Navigate(https://moskva.beeline.ru/login/)",

  "WaitVisible(input[id='userName'])",

  "SendKeys(input[id='userName'], $Login)",
  "Click(button[type='submit'])",

  "WaitVisible(a[role='button'])",
  "Click(a[role='button'])",

  "SendKeys(input[name='password'], $Password)",
  "Click(button[type='submit'])",

  "WaitVisible(div.Balance_infoValue_kVsT)",

  "Float(div.Balance_infoValue_kVsT, Баланс)",
  "String(td.Summary_profileInfoValue_1vmb > a > span, Тариф)",
]
