[operators.BEELINE]
description = "Билайн"
timeout = "300s"

tasks = [
  "Navigate(https://my.beeline.ru/login.xhtml)",
  "Clear(input[id='loginFormB2C:loginForm:login'])",

  "SendKeys(input[id='loginFormB2C:loginForm:login'], $Login)",
  "SendKeys(input[id='loginFormB2C:loginForm:passwordPwd'], $Password)",
  "Click(button[id='loginFormB2C:loginForm:j_idt212'])",

  "WaitVisible(div.Balance_infoValue_hPPq)",

  "Float(div.Balance_infoValue_hPPq, Баланс)",
  "String(tr.profileInfoRow > td.Summary_profileInfoValue_24h6 > a > span.Link_text_3wyt, Тариф)",
]
