[operators.BEELINE-MSK]
description = "Билайн-Москва"
timeout = "120s"

tasks = [
  "Option(blink-settings, imagesEnabled=true)",

  "Navigate(https://moskva.beeline.ru/login/)",

  "WaitVisible(div._g_BdN > p > a)",
  "Click(div._g_BdN > p > a)",

  "SendKeys(input[name='login'], $Login)",
  "SendKeys(input[name='password'], $Password)",
  "Click(span.yhMq_3)",

  "WaitVisible(div.Balance_infoValue_kVsT)",

  "Float(div.Balance_infoValue_kVsT, Баланс)",
  "String(td.Summary_profileInfoValue_1vmb > a > span, Тариф)",
]
