[operators.GISMETEO]
description = "Погода gismeteo.ru"
timeout = "30s"

tasks = [
  "Option(blink-settings, imagesEnabled=false)",
  "Navigate(https://gismeteo.ru/)",

  "Float(div.frame-now > div.weather-info-header > div.weather-temperature > div.temperature > span.unit_temperature_c, Температура)",
  "Float(div.weather-feeling  > div.item-value > span.unit_temperature_c, Температура по ощущению)",
  "Float(div.frame-now > div.weather-pressure > div.item-value > span.unit_pressure_mm_hg_atm, Давление)",
  "Float(div.frame-now > div.weather-humidity > div.item-value, Влажность)",
  "Float(div.frame-now > div.weather-wind > div.item-value > span.unit_wind_m_s, Ветер)",
  "String(a.city-link, Место)",
  "String(div.weather-description, Дополнительно)",
]
