[operators.MGTS]
description = "МГТС"
timeout = "30s"

tasks = [
  "Navigate(https://auth.mgts.ru/login/b2c?feature=lk)",

  "SendKeys(input[id='loginform-username'], $Login)",
  "Click(button[id='submit'])",

  "SendKeys(input[id='loginform-password'], $Password)",
  "Click(button[id='submit'])",

  "WaitVisible(div.account-info_balance_value)",

  "Float(div.account-info_balance_value span, Баланс)",
]
