[operators.MTS]
description = "МТС"
timeout = "60s"

tasks = [
  "Navigate(https://lk.mts.ru/)",

  "WaitVisible(input[id=login])",

  "SendKeys(input[id=login], $Login)",
  "Click(button[type=submit])",

  "WaitVisible(input[id=password])",

  "SendKeys(input[id=password], $Password)",
  "Click(button[type=submit])",

  "WaitVisible(span[class=widget-mobile-balance__value])",
  "Float(span[class=widget-mobile-balance__value], Баланс)",

  "String(div[class='widget-mobile-tariff__name ng-star-inserted'], Тариф)",
]
