[operators.MTS]
description = "МТС"
timeout = "30s"

tasks = [
  "Navigate(https://login.mts.ru/amserver/UI/Login?service=newlk&goto=https://lk.mts.ru/)",

  "SendKeys(input[id='phoneInput'], $Login)",
  "Submit(input[id='phoneInput'])",

  "SetValue(input[id='password'], $Password)",
  "Submit(input[id='password'])",

  "WaitVisible(div.parental-statistics-balance__item-summ span)",
  "WaitVisible(a.lk-tariff-info__title)",

  "Float(div.parental-statistics-balance__item-summ span, Баланс)",
  "String(a.lk-tariff-info__title, Тариф)",
]
