[operators.ONLIME]
description = "Onlime"
timeout = "60s"

tasks = [
  "Navigate(https://b2c.passport.rt.ru/auth/realms/b2c/protocol/openid-connect/auth/?client_id=lk_onlime&redirect_uri=https%3A%2F%2Fmy.rt.ru%2Fauth%2Fssoredirect%2F&response_type=code)",

  "WaitVisible(input[name='standard_auth_btn'])",
  "Click(input[id='standard_auth_btn'])",

  "WaitVisible([id='t-btn-tab-login'])",
  "Click(div[id='t-btn-tab-login'])",

  "SendKeys(input[name='name']   , $Login)",
  "SendKeys(input[name='password'], $Password)",
  "Click(input[name='login'])",

  "WaitVisible(div[id='account_info_block'] > div:nth-child(5) > p > big)",

  "Float(div[id='account_info_block'] > div:nth-child(5) > p > big, Баланс)",
  "Float(div[id='account_info_block'] > div:nth-child(6) > p > big, Бонусы)",
  "Float(div[id='account_info_block'] > div:nth-child(7) > p > span > big, Дней до блокировки)",
  "String(div[id='account_info_block'] > div:nth-child(8) > p:nth-child(2) > strong, Статус)",
]
