[operators.RUVDS]
description = "ruvds.com hosting provider"
timeout = "30s"

tasks = [
  "Navigate(https://ruvds.com/api/balance/?sessionToken={Token}&&details=0)",
  "Float(body, Баланс, json($.amount))",
  "Navigate(https://ruvds.com/api/servers/?sessionToken={Token}&id={ServerID})",
  "Float(body, Цена, json($.items[0].priceRub))",
  "Float(body, Входящий трафик, json($.items[0].stat.trafficInbound.value))",
  "Float(body, Исходящий трафик, json($.items[0].stat.trafficOutbound.value))",
  "String(body, Оплачено до, json($.items[0].paidTill))",
  "String(body, Уведомления, json($.items[0].notifications))",
]
