[operators.YOTA]
description = "Yota"
timeout = 30

tasks = [
  "Navigate(https://my.yota.ru/selfcare/login?goto=https%3A%2F%2Fmy.yota.ru%3A443%2Fdevices)",

  "SendKeys(input[name='phoneNumber'], $Login)",
  "SendKeys(input[name='password'], $Password)",
  "Click(button[type='submit'])",

  "Float(dd[id='balance-holder'] > span, Баланс)",
  "Float(div.tarriff-info > div.time > strong, Остаток дней)",
  "Float(div.tarriff-info > div.speed > strong, Скорость)",
  "Float(div.tarriff-info > div.cost > strong, Стоимость)",
]
