[operators.YOTA]
description = "Yota"
timeout = 30

tasks = [
  "Navigate(https://my.yota.ru/login?returnUrl=%2Fdevices)",

  "SendKeys(input[id='y-input-0'], $Login)",
  "SendKeys(input[id='y-input-1'], $Password)",
  "Click(button[class='y-m-8 y-button y-button-tiny'])",

  "Float(dd[id='balance-holder'] > span, Баланс)",
  "Float(div.tarriff-info > div.time > strong, Остаток дней)",
  "Float(div.tarriff-info > div.speed > strong, Скорость)",
  "Float(div.tarriff-info > div.cost > strong, Стоимость)",
]
