#----------------------------------------------------------------------------------------------------------------------------#

# Общие стандартные параметры

[common]
# Название приложения
name = "Balance collector"

# Описание приложения
description = "Balance collector"

# Класс приложения
class = "balance-collector"

{#include ^/common.toml}

#----------------------------------------------------------------------------------------------------------------------------#

# Параметры http интерфейса

[http]
# Листенер
listener = { \
	# Адрес, на котором слушать
	bind-addr = "127.0.0.1:{$PORT}", \

	# Префикс, который может добавляться прокси для идентификации приложения
	proxy-prefix = "/balance-collector/", \

	{#include ^/http.toml} \
}

#----------------------------------------------------------------------------------------------------------------------------#

[processor]
# По какой таймзоне работает расписание
# Local -- использовать устновленную на коммпьютере
cron-location = "Local"

# Расписание в формате cron по умолчанию
schedule = "12 5 * * *"

# Показывать браузер при работе
# Может потребоваться для отладки скриптов операторов
# При работе как сервис должно быть false
view-browser = {$VIEW_BROWSER}

# Каким браузером прикидываться, чтобы некоторые особо параноидальные операторы не отбивали запросы
user-agent   = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36"

# Стандартный таймаут ожидания ответа от оператора
std-timeout  = "60s"

# Имя базы данных для хранения истории
db = "@/balance-collector.db"

# Директория с шаблонами отчетов
templates-dir = "@/templates/"

#----------------------------------------------------------------------------------------------------------------------------#

# Скрипты операторов

{#include ^/operators/1vds.toml}
{#include ^/operators/beeline.toml}
{#include ^/operators/beeline-msk.toml}
{#include ^/operators/cbr.toml}
{#include ^/operators/gismeteo.toml}
{#include ^/operators/goodline.toml}
{#include ^/operators/mgts.toml}
{#include ^/operators/mts.toml}
{#include ^/operators/onlime.toml}
{#include ^/operators/rt.toml}
{#include ^/operators/ruvds.toml}
{#include ^/operators/tricolor.toml}
{#include ^/operators/yota.toml}

#----------------------------------------------------------------------------------------------------------------------------#

# Что надо использовать

{#include ^/entities.toml}

#----------------------------------------------------------------------------------------------------------------------------#
