[common]
name = "Balance collector"
description = "Balance collector"
class = ""

#log-local-time = true
log-dir = "logs"
log-level = "{$LOG_LEVEL}"
log-levels = {}
log-buffer-size = 0
log-buffer-delay = 0
log-max-string-len = 10000

#go-max-procs = 4

mem-stats-period = 1800
mem-stats-level = "INFO"

load-avg-period = 60

profiler-enabled = false 
deep-profiling = false

use-std-json = false

min-size-for-gzip = 256

#----------------------------------------------------------------------------------------------------------------------------#

[http]
listener = { \
	bind-addr = "127.0.0.1:{$PORT}", ssl-combined-pem = "", timeout = 5, \
	root = "html/", \
	proxy-prefix = "/balance-collector/", \
	icon-file = "$html/favicon.ico", \
	disabled-endpoints = [], \
	auth = { \
		endpoints = { "*" = ["admin"] }, \
		users = {{#include ^users.toml}}, \
		methods = { \
			basic = { enabled = false, score = 30, options = {} }, \
			jwt   = { enabled = false, score = 20, options = { secret = "?", lifetime = 157680000 } }, \
			krb5  = { enabled = false, score = 10, options = { key-file = "?" } }, \
		} \
	} \
}

#----------------------------------------------------------------------------------------------------------------------------#

[processor]
cron-location = "Local"
schedule = "12 5 * * *"

view-browser = {$VIEW_BROWSER}
user-agent   = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
std-timeout  = 60

db = "balance-collector.db"

templates-dir = "templates/"

#----------------------------------------------------------------------------------------------------------------------------#

{#include ^operators/1vds.toml}
{#include ^operators/beeline.toml}
{#include ^operators/cbr.toml}
{#include ^operators/gismeteo.toml}
{#include ^operators/goodline.toml}
{#include ^operators/mgts.toml}
{#include ^operators/mts.toml}
{#include ^operators/onlime.toml}
{#include ^operators/rt.toml}
{#include ^operators/tricolor.toml}
{#include ^operators/yota.toml}

#----------------------------------------------------------------------------------------------------------------------------#

{#include ^entities.toml}

#----------------------------------------------------------------------------------------------------------------------------#
