[[entities]]
# Внутренний уникальный идентификатор, любое число, не повторяющееся в других описаниях
id               = 1
# Разрешено?
enabled          = true
# Название
name             = "первый телефон"
# Описание
description      = "мой МТС"
# Тип (название оператора)
type             = "MTS"
# Расписание в формате cron, если пустая строка, то используется стандарное
schedule         = ""
# Задержка перед запросом. Может понадобится, если идет подряд несколько запросов к одному оператору, например на несколько телефонов. Некоторые из них это не любят.
delay            = "0s"
# Выделять в отчете, если первый получаемый параметр (обычно это баланс) больше этого значения. 0 -- не проверять
alert-level-high = 0
# Выделять в отчете, если первый получаемый параметр (обычно это баланс) меньше этого значения. 0 -- не проверять
alert-level-low  = 200
# Переменные для подстановки в шаблоны
vars = { \
	# Логин личного кабинета
	login            = "1234567890", \
	# Пароль личного кабинета
	password         = "SeCrEt-123", \
}

[[entities]]
id               = 2
enabled          = true
name             = "второй телефон"
description      = "мой второй МТС"
type             = "MTS"
schedule         = ""
delay            = "180s"
alert-level-high = 0
alert-level-low  = 200
vars = { \
	login    = "0987654321", \
	password = "SeCrEt-321", \
}

[[entities]]
id               = 100
enabled          = true
name             = "ЦБР USD&EUR"
description      = "Курсы ЦБР для USRRUR и EURRUR"
type             = "CBR"
schedule         = "58 11 * * 1-5"
delay            = "0s"
alert-level-high = 80
alert-level-low  = 70
vars = { \
}

[[entities]]
id               = 101
enabled          = true
name             = "Погода"
description      = "Погода gismeteo"
type             = "GISMETEO"
schedule         = "2 7,14,18,22 * * *"
delay            = "0s"
alert-level-high = 0
alert-level-low  = 0
vars = { \
}

